### PR TITLE
Add JWT token auth provider based on djangorestframework-simplejwt

### PR DESCRIPTION
**Pull request by barseghyanartur**
As proposed/discussed in #34

### CODE REVIEW

**Comment by bmihelac** [comment]
@barseghyanartur thanks for this pull request. 
Code looks good but I do not have an easy way to test. Do you think it would be easiest to add to jwt to [example](https://github.com/bmihelac/ra-data-django-rest-framework/tree/master/example/backend) app?

**Comment by barseghyanartur** [comment]
> @barseghyanartur thanks for this pull request.
> Code looks good but I do not have an easy way to test. Do you think it would be easiest to add to jwt to [example](https://github.com/bmihelac/ra-data-django-rest-framework/tree/master/example/backend) app?

Great! Thanks for checking. I thought tests should be sufficient, but sure - I will add a working example (later today/tomorrow) and let you know.

**Comment by barseghyanartur** [comment]
@bmihelac:

Example app is updated. Please, check.

**Comment by bmihelac** [comment]
@barseghyanartur merged, thanks!

**Comment by barseghyanartur** [comment]
@bmihelac:

Thanks! Could a npmjs release be expected one day soon? :)

**Pull request merged**
